/*
 * GPIO.cpp
 *
 * Created: 29.5.2023 8.34.05
 *  Author: home
 */ 
#include "IncFile1.h"

void init_pins(){
	

	PORTA_PIN1CTRL; //uart pin
	PORTA_PIN2CTRL; //uart pin
	PORTA_PIN3CTRL = PORT_ISC_INPUT_DISABLE_gc;
	PORTA_PIN4CTRL = PORT_ISC_INPUT_DISABLE_gc; // muxPOS
	PORTA_PIN5CTRL = PORT_ISC_INPUT_DISABLE_gc; //muxNEG
	PORTA_PIN6CTRL = PORT_PULLUPEN_bm | PORT_ISC_FALLING_gc; //button0
	PORTA_PIN7CTRL = PORT_ISC_INPUT_DISABLE_gc;
	
	PORTB_PIN0CTRL = PORT_ISC_INPUT_DISABLE_gc;
	PORTB_PIN1CTRL = PORT_ISC_INPUT_DISABLE_gc;
	PORTB_PIN2CTRL |= PORT_PULLUPEN_bm | PORT_ISC_FALLING_gc; //button1
	PORTB_PIN3CTRL = PORT_ISC_INPUT_DISABLE_gc; //timerA output
	
}